// flow-typed signature: 02c451acb1c4de7634a326adf3acc840
// flow-typed version: <<STUB>>/babel-preset-flow-vue_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-flow-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-flow-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-flow-vue/index' {
  declare module.exports: $Exports<'babel-preset-flow-vue'>;
}
declare module 'babel-preset-flow-vue/index.js' {
  declare module.exports: $Exports<'babel-preset-flow-vue'>;
}
