// flow-typed signature: 8d752e9e0fa7b49045bb264d72e6dbd4
// flow-typed version: <<STUB>>/electron-oauth-twitter_v^1.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-oauth-twitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-oauth-twitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-oauth-twitter/lib/OauthTwitter' {
  declare module.exports: any;
}

declare module 'electron-oauth-twitter/src/OauthTwitter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-oauth-twitter/lib/OauthTwitter.js' {
  declare module.exports: $Exports<'electron-oauth-twitter/lib/OauthTwitter'>;
}
declare module 'electron-oauth-twitter/src/OauthTwitter.js' {
  declare module.exports: $Exports<'electron-oauth-twitter/src/OauthTwitter'>;
}
