// flow-typed signature: efd2762c804ec860e93522f871924a84
// flow-typed version: <<STUB>>/electron-rebuild_v^1.1.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-rebuild'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-rebuild' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-rebuild/lib/cli' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/electron-locater' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/main' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/read-package-json' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/rebuild' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/cli' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/electron-locater' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/main' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/read-package-json' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/rebuild' {
  declare module.exports: any;
}

declare module 'electron-rebuild/test/electron-locater' {
  declare module.exports: any;
}

declare module 'electron-rebuild/test/read-package-json' {
  declare module.exports: any;
}

declare module 'electron-rebuild/test/rebuild' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-rebuild/lib/cli.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/cli'>;
}
declare module 'electron-rebuild/lib/electron-locater.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/electron-locater'>;
}
declare module 'electron-rebuild/lib/main.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/main'>;
}
declare module 'electron-rebuild/lib/read-package-json.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/read-package-json'>;
}
declare module 'electron-rebuild/lib/rebuild.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/rebuild'>;
}
declare module 'electron-rebuild/src/cli.js' {
  declare module.exports: $Exports<'electron-rebuild/src/cli'>;
}
declare module 'electron-rebuild/src/electron-locater.js' {
  declare module.exports: $Exports<'electron-rebuild/src/electron-locater'>;
}
declare module 'electron-rebuild/src/main.js' {
  declare module.exports: $Exports<'electron-rebuild/src/main'>;
}
declare module 'electron-rebuild/src/read-package-json.js' {
  declare module.exports: $Exports<'electron-rebuild/src/read-package-json'>;
}
declare module 'electron-rebuild/src/rebuild.js' {
  declare module.exports: $Exports<'electron-rebuild/src/rebuild'>;
}
declare module 'electron-rebuild/test/electron-locater.js' {
  declare module.exports: $Exports<'electron-rebuild/test/electron-locater'>;
}
declare module 'electron-rebuild/test/read-package-json.js' {
  declare module.exports: $Exports<'electron-rebuild/test/read-package-json'>;
}
declare module 'electron-rebuild/test/rebuild.js' {
  declare module.exports: $Exports<'electron-rebuild/test/rebuild'>;
}
