// flow-typed signature: 95f2ebd8a05897948bb1183d3418850b
// flow-typed version: <<STUB>>/eslint-plugin-html_v^2.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-html/src/__tests__/extract' {
  declare module.exports: any;
}

declare module 'eslint-plugin-html/src/__tests__/plugin' {
  declare module.exports: any;
}

declare module 'eslint-plugin-html/src/__tests__/TransformableString' {
  declare module.exports: any;
}

declare module 'eslint-plugin-html/src/extract' {
  declare module.exports: any;
}

declare module 'eslint-plugin-html/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-html/src/TransformableString' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-html/src/__tests__/extract.js' {
  declare module.exports: $Exports<'eslint-plugin-html/src/__tests__/extract'>;
}
declare module 'eslint-plugin-html/src/__tests__/plugin.js' {
  declare module.exports: $Exports<'eslint-plugin-html/src/__tests__/plugin'>;
}
declare module 'eslint-plugin-html/src/__tests__/TransformableString.js' {
  declare module.exports: $Exports<'eslint-plugin-html/src/__tests__/TransformableString'>;
}
declare module 'eslint-plugin-html/src/extract.js' {
  declare module.exports: $Exports<'eslint-plugin-html/src/extract'>;
}
declare module 'eslint-plugin-html/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-html/src/index'>;
}
declare module 'eslint-plugin-html/src/TransformableString.js' {
  declare module.exports: $Exports<'eslint-plugin-html/src/TransformableString'>;
}
