// flow-typed signature: bab5c67e8ea12282415741c890c987b1
// flow-typed version: <<STUB>>/eslint-friendly-formatter_v^2.0.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-friendly-formatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-friendly-formatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-friendly-formatter/process' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-friendly-formatter/index' {
  declare module.exports: $Exports<'eslint-friendly-formatter'>;
}
declare module 'eslint-friendly-formatter/index.js' {
  declare module.exports: $Exports<'eslint-friendly-formatter'>;
}
declare module 'eslint-friendly-formatter/process.js' {
  declare module.exports: $Exports<'eslint-friendly-formatter/process'>;
}
