// flow-typed signature: 937e1d648ceeccb5930c124cbed63605
// flow-typed version: <<STUB>>/eslint-plugin-vue_v^2.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-plugin-vue/index' {
  declare module.exports: $Exports<'eslint-plugin-vue'>;
}
declare module 'eslint-plugin-vue/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue'>;
}
