// flow-typed signature: 4889bf282e1d6d8ef0915c797fa2fef0
// flow-typed version: <<STUB>>/node-twitter-api_v^1.8.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-twitter-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-twitter-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-twitter-api/twitter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-twitter-api/index' {
  declare module.exports: $Exports<'node-twitter-api'>;
}
declare module 'node-twitter-api/index.js' {
  declare module.exports: $Exports<'node-twitter-api'>;
}
declare module 'node-twitter-api/twitter.js' {
  declare module.exports: $Exports<'node-twitter-api/twitter'>;
}
