// flow-typed signature: f94caf407134965dc86f3913ccd4a3ad
// flow-typed version: <<STUB>>/normalize.css_v^6.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
