// flow-typed signature: 8ff396745c28dfa865e87f48e022746b
// flow-typed version: <<STUB>>/normalize.css_v^6.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
