// flow-typed signature: aeb2085834bb8abdd420d7d192946c70
// flow-typed version: <<STUB>>/sweetalert_v^1.1.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sweetalert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sweetalert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sweetalert/dev/gulpfile-wrap-template' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/modules/default-params' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/modules/handle-click' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/modules/handle-dom' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/modules/handle-key' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/modules/handle-swal-dom' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/modules/injected-html' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/modules/set-params' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/modules/utils' {
  declare module.exports: any;
}

declare module 'sweetalert/dev/sweetalert.es6' {
  declare module.exports: any;
}

declare module 'sweetalert/dist/sweetalert-dev' {
  declare module.exports: any;
}

declare module 'sweetalert/dist/sweetalert.min' {
  declare module.exports: any;
}

declare module 'sweetalert/gulpfile' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/modules/default-params' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/modules/handle-click' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/modules/handle-dom' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/modules/handle-key' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/modules/handle-swal-dom' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/modules/injected-html' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/modules/set-params' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/modules/utils' {
  declare module.exports: any;
}

declare module 'sweetalert/lib/sweetalert' {
  declare module.exports: any;
}

declare module 'sweetalert/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sweetalert/dev/gulpfile-wrap-template.js' {
  declare module.exports: $Exports<'sweetalert/dev/gulpfile-wrap-template'>;
}
declare module 'sweetalert/dev/modules/default-params.js' {
  declare module.exports: $Exports<'sweetalert/dev/modules/default-params'>;
}
declare module 'sweetalert/dev/modules/handle-click.js' {
  declare module.exports: $Exports<'sweetalert/dev/modules/handle-click'>;
}
declare module 'sweetalert/dev/modules/handle-dom.js' {
  declare module.exports: $Exports<'sweetalert/dev/modules/handle-dom'>;
}
declare module 'sweetalert/dev/modules/handle-key.js' {
  declare module.exports: $Exports<'sweetalert/dev/modules/handle-key'>;
}
declare module 'sweetalert/dev/modules/handle-swal-dom.js' {
  declare module.exports: $Exports<'sweetalert/dev/modules/handle-swal-dom'>;
}
declare module 'sweetalert/dev/modules/injected-html.js' {
  declare module.exports: $Exports<'sweetalert/dev/modules/injected-html'>;
}
declare module 'sweetalert/dev/modules/set-params.js' {
  declare module.exports: $Exports<'sweetalert/dev/modules/set-params'>;
}
declare module 'sweetalert/dev/modules/utils.js' {
  declare module.exports: $Exports<'sweetalert/dev/modules/utils'>;
}
declare module 'sweetalert/dev/sweetalert.es6.js' {
  declare module.exports: $Exports<'sweetalert/dev/sweetalert.es6'>;
}
declare module 'sweetalert/dist/sweetalert-dev.js' {
  declare module.exports: $Exports<'sweetalert/dist/sweetalert-dev'>;
}
declare module 'sweetalert/dist/sweetalert.min.js' {
  declare module.exports: $Exports<'sweetalert/dist/sweetalert.min'>;
}
declare module 'sweetalert/gulpfile.js' {
  declare module.exports: $Exports<'sweetalert/gulpfile'>;
}
declare module 'sweetalert/lib/modules/default-params.js' {
  declare module.exports: $Exports<'sweetalert/lib/modules/default-params'>;
}
declare module 'sweetalert/lib/modules/handle-click.js' {
  declare module.exports: $Exports<'sweetalert/lib/modules/handle-click'>;
}
declare module 'sweetalert/lib/modules/handle-dom.js' {
  declare module.exports: $Exports<'sweetalert/lib/modules/handle-dom'>;
}
declare module 'sweetalert/lib/modules/handle-key.js' {
  declare module.exports: $Exports<'sweetalert/lib/modules/handle-key'>;
}
declare module 'sweetalert/lib/modules/handle-swal-dom.js' {
  declare module.exports: $Exports<'sweetalert/lib/modules/handle-swal-dom'>;
}
declare module 'sweetalert/lib/modules/injected-html.js' {
  declare module.exports: $Exports<'sweetalert/lib/modules/injected-html'>;
}
declare module 'sweetalert/lib/modules/set-params.js' {
  declare module.exports: $Exports<'sweetalert/lib/modules/set-params'>;
}
declare module 'sweetalert/lib/modules/utils.js' {
  declare module.exports: $Exports<'sweetalert/lib/modules/utils'>;
}
declare module 'sweetalert/lib/sweetalert.js' {
  declare module.exports: $Exports<'sweetalert/lib/sweetalert'>;
}
declare module 'sweetalert/test/tests.js' {
  declare module.exports: $Exports<'sweetalert/test/tests'>;
}
