// flow-typed signature: c62e8eb6b1d05de42a7950665b9b9d87
// flow-typed version: <<STUB>>/tether_v^1.4.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tether'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tether' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tether/dist/js/tether' {
  declare module.exports: any;
}

declare module 'tether/dist/js/tether.min' {
  declare module.exports: any;
}

declare module 'tether/docs/js/intro' {
  declare module.exports: any;
}

declare module 'tether/docs/js/markAttachment' {
  declare module.exports: any;
}

declare module 'tether/docs/welcome/js/drop' {
  declare module.exports: any;
}

declare module 'tether/docs/welcome/js/jquery' {
  declare module.exports: any;
}

declare module 'tether/docs/welcome/js/log' {
  declare module.exports: any;
}

declare module 'tether/docs/welcome/js/tether-v0.1.3' {
  declare module.exports: any;
}

declare module 'tether/docs/welcome/js/welcome' {
  declare module.exports: any;
}

declare module 'tether/examples/chosen/chosen' {
  declare module.exports: any;
}

declare module 'tether/examples/dolls/dolls' {
  declare module.exports: any;
}

declare module 'tether/examples/resources/js/jquery' {
  declare module.exports: any;
}

declare module 'tether/examples/resources/js/log' {
  declare module.exports: any;
}

declare module 'tether/gulpfile' {
  declare module.exports: any;
}

declare module 'tether/src/js/abutment' {
  declare module.exports: any;
}

declare module 'tether/src/js/constraint' {
  declare module.exports: any;
}

declare module 'tether/src/js/markAttachment' {
  declare module.exports: any;
}

declare module 'tether/src/js/shift' {
  declare module.exports: any;
}

declare module 'tether/src/js/tether' {
  declare module.exports: any;
}

declare module 'tether/src/js/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tether/dist/js/tether.js' {
  declare module.exports: $Exports<'tether/dist/js/tether'>;
}
declare module 'tether/dist/js/tether.min.js' {
  declare module.exports: $Exports<'tether/dist/js/tether.min'>;
}
declare module 'tether/docs/js/intro.js' {
  declare module.exports: $Exports<'tether/docs/js/intro'>;
}
declare module 'tether/docs/js/markAttachment.js' {
  declare module.exports: $Exports<'tether/docs/js/markAttachment'>;
}
declare module 'tether/docs/welcome/js/drop.js' {
  declare module.exports: $Exports<'tether/docs/welcome/js/drop'>;
}
declare module 'tether/docs/welcome/js/jquery.js' {
  declare module.exports: $Exports<'tether/docs/welcome/js/jquery'>;
}
declare module 'tether/docs/welcome/js/log.js' {
  declare module.exports: $Exports<'tether/docs/welcome/js/log'>;
}
declare module 'tether/docs/welcome/js/tether-v0.1.3.js' {
  declare module.exports: $Exports<'tether/docs/welcome/js/tether-v0.1.3'>;
}
declare module 'tether/docs/welcome/js/welcome.js' {
  declare module.exports: $Exports<'tether/docs/welcome/js/welcome'>;
}
declare module 'tether/examples/chosen/chosen.js' {
  declare module.exports: $Exports<'tether/examples/chosen/chosen'>;
}
declare module 'tether/examples/dolls/dolls.js' {
  declare module.exports: $Exports<'tether/examples/dolls/dolls'>;
}
declare module 'tether/examples/resources/js/jquery.js' {
  declare module.exports: $Exports<'tether/examples/resources/js/jquery'>;
}
declare module 'tether/examples/resources/js/log.js' {
  declare module.exports: $Exports<'tether/examples/resources/js/log'>;
}
declare module 'tether/gulpfile.js' {
  declare module.exports: $Exports<'tether/gulpfile'>;
}
declare module 'tether/src/js/abutment.js' {
  declare module.exports: $Exports<'tether/src/js/abutment'>;
}
declare module 'tether/src/js/constraint.js' {
  declare module.exports: $Exports<'tether/src/js/constraint'>;
}
declare module 'tether/src/js/markAttachment.js' {
  declare module.exports: $Exports<'tether/src/js/markAttachment'>;
}
declare module 'tether/src/js/shift.js' {
  declare module.exports: $Exports<'tether/src/js/shift'>;
}
declare module 'tether/src/js/tether.js' {
  declare module.exports: $Exports<'tether/src/js/tether'>;
}
declare module 'tether/src/js/utils.js' {
  declare module.exports: $Exports<'tether/src/js/utils'>;
}
