// flow-typed signature: 61e86fbb30b1569580d0895d9335356d
// flow-typed version: <<STUB>>/types_v^0.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'types/lib/types' {
  declare module.exports: any;
}

declare module 'types/lib/types/hash' {
  declare module.exports: any;
}

declare module 'types/lib/types/set' {
  declare module.exports: any;
}

declare module 'types/lib/types/sorted_list' {
  declare module.exports: any;
}

declare module 'types/test/hash-test' {
  declare module.exports: any;
}

declare module 'types/test/sorted_list-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'types/index' {
  declare module.exports: $Exports<'types'>;
}
declare module 'types/index.js' {
  declare module.exports: $Exports<'types'>;
}
declare module 'types/lib/types.js' {
  declare module.exports: $Exports<'types/lib/types'>;
}
declare module 'types/lib/types/hash.js' {
  declare module.exports: $Exports<'types/lib/types/hash'>;
}
declare module 'types/lib/types/set.js' {
  declare module.exports: $Exports<'types/lib/types/set'>;
}
declare module 'types/lib/types/sorted_list.js' {
  declare module.exports: $Exports<'types/lib/types/sorted_list'>;
}
declare module 'types/test/hash-test.js' {
  declare module.exports: $Exports<'types/test/hash-test'>;
}
declare module 'types/test/sorted_list-test.js' {
  declare module.exports: $Exports<'types/test/sorted_list-test'>;
}
