// flow-typed signature: 18fd2a081203717a9545d726fd96f618
// flow-typed version: <<STUB>>/vue-hot-reload-api_v^2.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-hot-reload-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-hot-reload-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vue-hot-reload-api/index' {
  declare module.exports: $Exports<'vue-hot-reload-api'>;
}
declare module 'vue-hot-reload-api/index.js' {
  declare module.exports: $Exports<'vue-hot-reload-api'>;
}
