// flow-typed signature: 37ad1e3aafae8f4666e7e2c0e8ac06a5
// flow-typed version: <<STUB>>/vue-html-loader_v^1.2.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-html-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-html-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-html-loader/lib/attributesParser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-html-loader/index' {
  declare module.exports: $Exports<'vue-html-loader'>;
}
declare module 'vue-html-loader/index.js' {
  declare module.exports: $Exports<'vue-html-loader'>;
}
declare module 'vue-html-loader/lib/attributesParser.js' {
  declare module.exports: $Exports<'vue-html-loader/lib/attributesParser'>;
}
