// flow-typed signature: 2dd4a58151a2608fa3e8daf2b88cdbd7
// flow-typed version: <<STUB>>/vue-lazyload_v^1.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-lazyload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-lazyload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-lazyload/build' {
  declare module.exports: any;
}

declare module 'vue-lazyload/src/index' {
  declare module.exports: any;
}

declare module 'vue-lazyload/src/lazy-component' {
  declare module.exports: any;
}

declare module 'vue-lazyload/src/lazy' {
  declare module.exports: any;
}

declare module 'vue-lazyload/src/listener' {
  declare module.exports: any;
}

declare module 'vue-lazyload/src/util' {
  declare module.exports: any;
}

declare module 'vue-lazyload/vue-lazyload' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-lazyload/build.js' {
  declare module.exports: $Exports<'vue-lazyload/build'>;
}
declare module 'vue-lazyload/src/index.js' {
  declare module.exports: $Exports<'vue-lazyload/src/index'>;
}
declare module 'vue-lazyload/src/lazy-component.js' {
  declare module.exports: $Exports<'vue-lazyload/src/lazy-component'>;
}
declare module 'vue-lazyload/src/lazy.js' {
  declare module.exports: $Exports<'vue-lazyload/src/lazy'>;
}
declare module 'vue-lazyload/src/listener.js' {
  declare module.exports: $Exports<'vue-lazyload/src/listener'>;
}
declare module 'vue-lazyload/src/util.js' {
  declare module.exports: $Exports<'vue-lazyload/src/util'>;
}
declare module 'vue-lazyload/vue-lazyload.js' {
  declare module.exports: $Exports<'vue-lazyload/vue-lazyload'>;
}
