// flow-typed signature: 792be8e5f332f32a337a8c34dfbe25ed
// flow-typed version: <<STUB>>/vue-material_v^0.7.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-material'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-material' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-material/dist/components/mdAvatar/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdAvatar/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdBackdrop/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdBackdrop/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdBottomBar/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdBottomBar/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdButton/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdButton/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdButtonToggle/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdButtonToggle/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdCard/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdCard/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdCheckbox/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdCheckbox/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdChips/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdChips/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdCore/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdCore/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdDialog/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdDialog/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdDivider/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdDivider/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdFile/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdFile/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdIcon/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdIcon/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdImage/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdImage/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdInputContainer/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdInputContainer/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdLayout/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdLayout/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdList/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdList/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdMenu/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdMenu/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdProgress/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdProgress/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdRadio/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdRadio/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSelect/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSelect/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSidenav/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSidenav/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSnackbar/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSnackbar/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSpeedDial/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSpeedDial/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSpinner/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSpinner/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSubheader/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSubheader/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSwitch/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdSwitch/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdTable/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdTable/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdTabs/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdTabs/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdToolbar/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdToolbar/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdTooltip/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdTooltip/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdWhiteframe/index.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/components/mdWhiteframe/index' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/avatar.1c2ea266' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/base.468dbabb' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/bottom-bar.d91c96eb' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/button-toggle.c6150e67' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/buttons.b9a70faf' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/card.813a55b3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/checkbox.3d60ec17' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/chips.0dd4d690' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/dialog.d27bc67f' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/docs.ef570dcd' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/file.05ab386d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/icon.9c317d12' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/image-loader.6a229b14' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/ink-ripple.2e814707' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/input.76e80edc' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/list.93bce61c' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/manifest.1e83b2d7' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/menu.66f674a5' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/progress.dbae7eff' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/radio.0d3a1cf9' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.1/docs.93264ef9' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.1/manifest.d93d0eda' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.1/vendor.2044b105' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/0.cf567cfa' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/1.aebda25a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/10.d6e091c7' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/11.57baa516' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/12.412e420a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/13.10c43d78' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/14.b700e246' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/15.0f0501f9' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/16.7eaf3c08' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/17.bef219a0' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/18.d5035c12' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/19.88ab05fd' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/2.b62f9e71' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/20.0980afec' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/21.6999e85f' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/22.838a8032' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/23.91e06240' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/24.38594b9c' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/25.0a12003e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/26.ce0a9d8d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/3.24b8259b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/4.dda87c6e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/5.4f97396d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/6.914fc411' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/7.43232ee9' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/8.19299e2b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/9.7a6b4c90' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/docs.80bc43c9' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/manifest.013bc964' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.5.2/vendor.1366249b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/0.8985122d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/1.06ee0bed' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/10.c7e6c3e5' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/11.fd21e8e8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/12.cb3c1a2d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/13.1cdad18e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/14.fd41ec35' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/15.58889e3a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/16.e2efe67b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/17.0d923825' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/18.fa7c7df1' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/19.62eeb5ff' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/2.c10fbd04' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/20.861ee4ae' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/21.9fa5a6ef' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/22.5475b341' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/23.56fe1118' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/24.d3091d84' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/25.bb881f9f' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/26.6c68ad23' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/27.dac46d92' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/28.3b5484f8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/29.cf5daabc' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/3.937606f3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/30.a9cd11af' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/31.111340a6' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/4.94654a0e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/5.f8a38ce8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/6.6d779ad8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/7.fea19aba' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/8.4a1e48b3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/9.3f930309' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/docs.3e2ba22f' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/manifest.5f563a9d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.0/vendor.ae4be299' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/0.8985122d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/1.06ee0bed' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/10.c7e6c3e5' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/11.fd21e8e8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/12.cb3c1a2d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/13.1cdad18e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/14.fd41ec35' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/15.58889e3a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/16.e2efe67b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/17.0d923825' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/18.fa7c7df1' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/19.62eeb5ff' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/2.c10fbd04' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/20.861ee4ae' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/21.9fa5a6ef' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/22.5475b341' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/23.56fe1118' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/24.d3091d84' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/25.bb881f9f' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/26.6c68ad23' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/27.dac46d92' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/28.3b5484f8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/29.cf5daabc' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/3.937606f3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/30.a9cd11af' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/31.111340a6' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/4.94654a0e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/5.f8a38ce8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/6.6d779ad8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/7.fea19aba' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/8.4a1e48b3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/9.3f930309' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/docs.2897e9e6' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/manifest.b7f52b44' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.1/vendor.ae4be299' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/0.8985122d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/1.06ee0bed' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/10.c7e6c3e5' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/11.fd21e8e8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/12.cb3c1a2d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/13.1cdad18e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/14.fd41ec35' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/15.58889e3a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/16.e2efe67b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/17.0d923825' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/18.fa7c7df1' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/19.62eeb5ff' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/2.c10fbd04' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/20.861ee4ae' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/21.9fa5a6ef' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/22.5475b341' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/23.56fe1118' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/24.d3091d84' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/25.bb881f9f' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/26.6c68ad23' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/27.dac46d92' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/28.3b5484f8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/29.cf5daabc' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/3.937606f3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/30.a9cd11af' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/31.111340a6' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/4.94654a0e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/5.f8a38ce8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/6.6d779ad8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/7.fea19aba' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/8.4a1e48b3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/9.3f930309' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/docs.2897e9e6' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/manifest.b7f52b44' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.2/vendor.ae4be299' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/0.8985122d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/1.06ee0bed' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/10.c7e6c3e5' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/11.fd21e8e8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/12.cb3c1a2d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/13.1cdad18e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/14.fd41ec35' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/15.58889e3a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/16.e2efe67b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/17.0d923825' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/18.fa7c7df1' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/19.62eeb5ff' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/2.c10fbd04' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/20.861ee4ae' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/21.9fa5a6ef' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/22.5475b341' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/23.56fe1118' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/24.d3091d84' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/25.bb881f9f' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/26.6c68ad23' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/27.dac46d92' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/28.3b5484f8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/29.cf5daabc' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/3.937606f3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/30.a9cd11af' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/31.111340a6' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/4.94654a0e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/5.f8a38ce8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/6.6d779ad8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/7.fea19aba' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/8.4a1e48b3' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/9.3f930309' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/docs.abaf0d65' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/manifest.2b0afab6' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.6.3/vendor.ae4be299' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/avatar.a4498c8a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/base.695f7a2d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/bottom-bar.e6f88ccc' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/button-toggle.5458c921' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/buttons.81edf435' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/card.37f54da4' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/checkbox.7603dc1d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/chips.996b2d4b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/dialog.774bdbaf' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/docs.478f64a5' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/file.e75792b4' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/icon.5330687d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/image-loader.2b5a107e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/ink-ripple.c6c186b1' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/input.ecca7906' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/list.21d93484' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/manifest.09510f01' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/menu.212fadff' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/progress.2ff899d0' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/radio.da972ed8' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/select.bff7868d' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/sidenav.5443196c' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/snackbar.00a46162' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/speed-dial.e07af350' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/spinner.ae9c0ffa' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/subheader.f0a1356a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/switch.9aa0318e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/table.295127fd' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/tabs.b3bab112' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/themes.cef94272' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/toolbar.44924cd1' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/tooltip.1eae832b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/ui-elements.ac4dc67a' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/vendor.51aac3ed' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/releases/v0.7.0/whiteframe.7fa045b4' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/select.a1466fb5' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/sidenav.fba2cd03' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/snackbar.f7ea4b33' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/speed-dial.dd03eb33' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/spinner.43051fb4' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/subheader.5d412f8e' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/switch.4548de27' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/table.0fb9c164' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/tabs.5e48770b' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/themes.614919f9' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/toolbar.caa5dc64' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/tooltip.0834711f' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/ui-elements.775ab723' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/vendor.a3c44323' {
  declare module.exports: any;
}

declare module 'vue-material/dist/docs/whiteframe.65446ff4' {
  declare module.exports: any;
}

declare module 'vue-material/dist/vue-material.debug' {
  declare module.exports: any;
}

declare module 'vue-material/dist/vue-material' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdAvatar/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdBackdrop/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdBottomBar/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdButton/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdButtonToggle/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdCard/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdCheckbox/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdChips/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdDialog/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdDivider/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdFile/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdIcon/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdImage/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdInputContainer/common' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdInputContainer/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdLayout/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdList/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdList/mdListItem' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdMenu/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdProgress/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdRadio/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdSelect/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdSidenav/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdSnackbar/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdSnackbar/manager' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdSpeedDial/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdSpinner/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdSubheader/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdSwitch/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdTable/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdTabs/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdToolbar/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdTooltip/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/components/mdWhiteframe/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/components/mdInkRipple/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/components/mdTheme/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/components/mdTheme/mixin' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/components/mdTheme/palette' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/components/mdTheme/rgba' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/index' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/animationEndEventName' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/debounce' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/getClosestVueParent' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/getImageLightness' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/getInViewPosition' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/isArray' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/throttle' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/transitionEndEventName' {
  declare module.exports: any;
}

declare module 'vue-material/src/core/utils/uniqueId' {
  declare module.exports: any;
}

declare module 'vue-material/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-material/dist/components/mdAvatar/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdAvatar/index.debug'>;
}
declare module 'vue-material/dist/components/mdAvatar/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdAvatar/index'>;
}
declare module 'vue-material/dist/components/mdBackdrop/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdBackdrop/index.debug'>;
}
declare module 'vue-material/dist/components/mdBackdrop/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdBackdrop/index'>;
}
declare module 'vue-material/dist/components/mdBottomBar/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdBottomBar/index.debug'>;
}
declare module 'vue-material/dist/components/mdBottomBar/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdBottomBar/index'>;
}
declare module 'vue-material/dist/components/mdButton/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdButton/index.debug'>;
}
declare module 'vue-material/dist/components/mdButton/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdButton/index'>;
}
declare module 'vue-material/dist/components/mdButtonToggle/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdButtonToggle/index.debug'>;
}
declare module 'vue-material/dist/components/mdButtonToggle/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdButtonToggle/index'>;
}
declare module 'vue-material/dist/components/mdCard/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdCard/index.debug'>;
}
declare module 'vue-material/dist/components/mdCard/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdCard/index'>;
}
declare module 'vue-material/dist/components/mdCheckbox/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdCheckbox/index.debug'>;
}
declare module 'vue-material/dist/components/mdCheckbox/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdCheckbox/index'>;
}
declare module 'vue-material/dist/components/mdChips/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdChips/index.debug'>;
}
declare module 'vue-material/dist/components/mdChips/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdChips/index'>;
}
declare module 'vue-material/dist/components/mdCore/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdCore/index.debug'>;
}
declare module 'vue-material/dist/components/mdCore/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdCore/index'>;
}
declare module 'vue-material/dist/components/mdDialog/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdDialog/index.debug'>;
}
declare module 'vue-material/dist/components/mdDialog/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdDialog/index'>;
}
declare module 'vue-material/dist/components/mdDivider/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdDivider/index.debug'>;
}
declare module 'vue-material/dist/components/mdDivider/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdDivider/index'>;
}
declare module 'vue-material/dist/components/mdFile/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdFile/index.debug'>;
}
declare module 'vue-material/dist/components/mdFile/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdFile/index'>;
}
declare module 'vue-material/dist/components/mdIcon/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdIcon/index.debug'>;
}
declare module 'vue-material/dist/components/mdIcon/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdIcon/index'>;
}
declare module 'vue-material/dist/components/mdImage/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdImage/index.debug'>;
}
declare module 'vue-material/dist/components/mdImage/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdImage/index'>;
}
declare module 'vue-material/dist/components/mdInputContainer/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdInputContainer/index.debug'>;
}
declare module 'vue-material/dist/components/mdInputContainer/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdInputContainer/index'>;
}
declare module 'vue-material/dist/components/mdLayout/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdLayout/index.debug'>;
}
declare module 'vue-material/dist/components/mdLayout/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdLayout/index'>;
}
declare module 'vue-material/dist/components/mdList/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdList/index.debug'>;
}
declare module 'vue-material/dist/components/mdList/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdList/index'>;
}
declare module 'vue-material/dist/components/mdMenu/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdMenu/index.debug'>;
}
declare module 'vue-material/dist/components/mdMenu/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdMenu/index'>;
}
declare module 'vue-material/dist/components/mdProgress/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdProgress/index.debug'>;
}
declare module 'vue-material/dist/components/mdProgress/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdProgress/index'>;
}
declare module 'vue-material/dist/components/mdRadio/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdRadio/index.debug'>;
}
declare module 'vue-material/dist/components/mdRadio/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdRadio/index'>;
}
declare module 'vue-material/dist/components/mdSelect/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSelect/index.debug'>;
}
declare module 'vue-material/dist/components/mdSelect/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSelect/index'>;
}
declare module 'vue-material/dist/components/mdSidenav/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSidenav/index.debug'>;
}
declare module 'vue-material/dist/components/mdSidenav/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSidenav/index'>;
}
declare module 'vue-material/dist/components/mdSnackbar/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSnackbar/index.debug'>;
}
declare module 'vue-material/dist/components/mdSnackbar/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSnackbar/index'>;
}
declare module 'vue-material/dist/components/mdSpeedDial/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSpeedDial/index.debug'>;
}
declare module 'vue-material/dist/components/mdSpeedDial/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSpeedDial/index'>;
}
declare module 'vue-material/dist/components/mdSpinner/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSpinner/index.debug'>;
}
declare module 'vue-material/dist/components/mdSpinner/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSpinner/index'>;
}
declare module 'vue-material/dist/components/mdSubheader/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSubheader/index.debug'>;
}
declare module 'vue-material/dist/components/mdSubheader/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSubheader/index'>;
}
declare module 'vue-material/dist/components/mdSwitch/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSwitch/index.debug'>;
}
declare module 'vue-material/dist/components/mdSwitch/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdSwitch/index'>;
}
declare module 'vue-material/dist/components/mdTable/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdTable/index.debug'>;
}
declare module 'vue-material/dist/components/mdTable/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdTable/index'>;
}
declare module 'vue-material/dist/components/mdTabs/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdTabs/index.debug'>;
}
declare module 'vue-material/dist/components/mdTabs/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdTabs/index'>;
}
declare module 'vue-material/dist/components/mdToolbar/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdToolbar/index.debug'>;
}
declare module 'vue-material/dist/components/mdToolbar/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdToolbar/index'>;
}
declare module 'vue-material/dist/components/mdTooltip/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdTooltip/index.debug'>;
}
declare module 'vue-material/dist/components/mdTooltip/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdTooltip/index'>;
}
declare module 'vue-material/dist/components/mdWhiteframe/index.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdWhiteframe/index.debug'>;
}
declare module 'vue-material/dist/components/mdWhiteframe/index.js' {
  declare module.exports: $Exports<'vue-material/dist/components/mdWhiteframe/index'>;
}
declare module 'vue-material/dist/docs/avatar.1c2ea266.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/avatar.1c2ea266'>;
}
declare module 'vue-material/dist/docs/base.468dbabb.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/base.468dbabb'>;
}
declare module 'vue-material/dist/docs/bottom-bar.d91c96eb.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/bottom-bar.d91c96eb'>;
}
declare module 'vue-material/dist/docs/button-toggle.c6150e67.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/button-toggle.c6150e67'>;
}
declare module 'vue-material/dist/docs/buttons.b9a70faf.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/buttons.b9a70faf'>;
}
declare module 'vue-material/dist/docs/card.813a55b3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/card.813a55b3'>;
}
declare module 'vue-material/dist/docs/checkbox.3d60ec17.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/checkbox.3d60ec17'>;
}
declare module 'vue-material/dist/docs/chips.0dd4d690.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/chips.0dd4d690'>;
}
declare module 'vue-material/dist/docs/dialog.d27bc67f.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/dialog.d27bc67f'>;
}
declare module 'vue-material/dist/docs/docs.ef570dcd.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/docs.ef570dcd'>;
}
declare module 'vue-material/dist/docs/file.05ab386d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/file.05ab386d'>;
}
declare module 'vue-material/dist/docs/icon.9c317d12.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/icon.9c317d12'>;
}
declare module 'vue-material/dist/docs/image-loader.6a229b14.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/image-loader.6a229b14'>;
}
declare module 'vue-material/dist/docs/ink-ripple.2e814707.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/ink-ripple.2e814707'>;
}
declare module 'vue-material/dist/docs/input.76e80edc.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/input.76e80edc'>;
}
declare module 'vue-material/dist/docs/list.93bce61c.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/list.93bce61c'>;
}
declare module 'vue-material/dist/docs/manifest.1e83b2d7.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/manifest.1e83b2d7'>;
}
declare module 'vue-material/dist/docs/menu.66f674a5.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/menu.66f674a5'>;
}
declare module 'vue-material/dist/docs/progress.dbae7eff.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/progress.dbae7eff'>;
}
declare module 'vue-material/dist/docs/radio.0d3a1cf9.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/radio.0d3a1cf9'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.1/docs.93264ef9.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.1/docs.93264ef9'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.1/manifest.d93d0eda.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.1/manifest.d93d0eda'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.1/vendor.2044b105.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.1/vendor.2044b105'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/0.cf567cfa.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/0.cf567cfa'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/1.aebda25a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/1.aebda25a'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/10.d6e091c7.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/10.d6e091c7'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/11.57baa516.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/11.57baa516'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/12.412e420a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/12.412e420a'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/13.10c43d78.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/13.10c43d78'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/14.b700e246.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/14.b700e246'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/15.0f0501f9.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/15.0f0501f9'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/16.7eaf3c08.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/16.7eaf3c08'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/17.bef219a0.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/17.bef219a0'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/18.d5035c12.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/18.d5035c12'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/19.88ab05fd.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/19.88ab05fd'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/2.b62f9e71.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/2.b62f9e71'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/20.0980afec.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/20.0980afec'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/21.6999e85f.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/21.6999e85f'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/22.838a8032.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/22.838a8032'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/23.91e06240.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/23.91e06240'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/24.38594b9c.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/24.38594b9c'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/25.0a12003e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/25.0a12003e'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/26.ce0a9d8d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/26.ce0a9d8d'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/3.24b8259b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/3.24b8259b'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/4.dda87c6e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/4.dda87c6e'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/5.4f97396d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/5.4f97396d'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/6.914fc411.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/6.914fc411'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/7.43232ee9.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/7.43232ee9'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/8.19299e2b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/8.19299e2b'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/9.7a6b4c90.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/9.7a6b4c90'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/docs.80bc43c9.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/docs.80bc43c9'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/manifest.013bc964.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/manifest.013bc964'>;
}
declare module 'vue-material/dist/docs/releases/v0.5.2/vendor.1366249b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.5.2/vendor.1366249b'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/0.8985122d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/0.8985122d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/1.06ee0bed.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/1.06ee0bed'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/10.c7e6c3e5.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/10.c7e6c3e5'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/11.fd21e8e8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/11.fd21e8e8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/12.cb3c1a2d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/12.cb3c1a2d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/13.1cdad18e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/13.1cdad18e'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/14.fd41ec35.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/14.fd41ec35'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/15.58889e3a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/15.58889e3a'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/16.e2efe67b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/16.e2efe67b'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/17.0d923825.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/17.0d923825'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/18.fa7c7df1.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/18.fa7c7df1'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/19.62eeb5ff.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/19.62eeb5ff'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/2.c10fbd04.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/2.c10fbd04'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/20.861ee4ae.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/20.861ee4ae'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/21.9fa5a6ef.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/21.9fa5a6ef'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/22.5475b341.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/22.5475b341'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/23.56fe1118.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/23.56fe1118'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/24.d3091d84.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/24.d3091d84'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/25.bb881f9f.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/25.bb881f9f'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/26.6c68ad23.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/26.6c68ad23'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/27.dac46d92.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/27.dac46d92'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/28.3b5484f8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/28.3b5484f8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/29.cf5daabc.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/29.cf5daabc'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/3.937606f3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/3.937606f3'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/30.a9cd11af.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/30.a9cd11af'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/31.111340a6.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/31.111340a6'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/4.94654a0e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/4.94654a0e'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/5.f8a38ce8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/5.f8a38ce8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/6.6d779ad8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/6.6d779ad8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/7.fea19aba.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/7.fea19aba'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/8.4a1e48b3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/8.4a1e48b3'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/9.3f930309.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/9.3f930309'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/docs.3e2ba22f.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/docs.3e2ba22f'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/manifest.5f563a9d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/manifest.5f563a9d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.0/vendor.ae4be299.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.0/vendor.ae4be299'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/0.8985122d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/0.8985122d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/1.06ee0bed.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/1.06ee0bed'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/10.c7e6c3e5.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/10.c7e6c3e5'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/11.fd21e8e8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/11.fd21e8e8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/12.cb3c1a2d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/12.cb3c1a2d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/13.1cdad18e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/13.1cdad18e'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/14.fd41ec35.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/14.fd41ec35'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/15.58889e3a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/15.58889e3a'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/16.e2efe67b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/16.e2efe67b'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/17.0d923825.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/17.0d923825'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/18.fa7c7df1.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/18.fa7c7df1'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/19.62eeb5ff.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/19.62eeb5ff'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/2.c10fbd04.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/2.c10fbd04'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/20.861ee4ae.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/20.861ee4ae'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/21.9fa5a6ef.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/21.9fa5a6ef'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/22.5475b341.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/22.5475b341'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/23.56fe1118.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/23.56fe1118'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/24.d3091d84.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/24.d3091d84'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/25.bb881f9f.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/25.bb881f9f'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/26.6c68ad23.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/26.6c68ad23'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/27.dac46d92.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/27.dac46d92'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/28.3b5484f8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/28.3b5484f8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/29.cf5daabc.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/29.cf5daabc'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/3.937606f3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/3.937606f3'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/30.a9cd11af.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/30.a9cd11af'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/31.111340a6.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/31.111340a6'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/4.94654a0e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/4.94654a0e'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/5.f8a38ce8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/5.f8a38ce8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/6.6d779ad8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/6.6d779ad8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/7.fea19aba.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/7.fea19aba'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/8.4a1e48b3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/8.4a1e48b3'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/9.3f930309.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/9.3f930309'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/docs.2897e9e6.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/docs.2897e9e6'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/manifest.b7f52b44.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/manifest.b7f52b44'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.1/vendor.ae4be299.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.1/vendor.ae4be299'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/0.8985122d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/0.8985122d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/1.06ee0bed.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/1.06ee0bed'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/10.c7e6c3e5.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/10.c7e6c3e5'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/11.fd21e8e8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/11.fd21e8e8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/12.cb3c1a2d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/12.cb3c1a2d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/13.1cdad18e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/13.1cdad18e'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/14.fd41ec35.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/14.fd41ec35'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/15.58889e3a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/15.58889e3a'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/16.e2efe67b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/16.e2efe67b'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/17.0d923825.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/17.0d923825'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/18.fa7c7df1.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/18.fa7c7df1'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/19.62eeb5ff.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/19.62eeb5ff'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/2.c10fbd04.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/2.c10fbd04'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/20.861ee4ae.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/20.861ee4ae'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/21.9fa5a6ef.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/21.9fa5a6ef'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/22.5475b341.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/22.5475b341'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/23.56fe1118.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/23.56fe1118'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/24.d3091d84.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/24.d3091d84'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/25.bb881f9f.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/25.bb881f9f'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/26.6c68ad23.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/26.6c68ad23'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/27.dac46d92.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/27.dac46d92'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/28.3b5484f8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/28.3b5484f8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/29.cf5daabc.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/29.cf5daabc'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/3.937606f3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/3.937606f3'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/30.a9cd11af.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/30.a9cd11af'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/31.111340a6.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/31.111340a6'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/4.94654a0e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/4.94654a0e'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/5.f8a38ce8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/5.f8a38ce8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/6.6d779ad8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/6.6d779ad8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/7.fea19aba.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/7.fea19aba'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/8.4a1e48b3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/8.4a1e48b3'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/9.3f930309.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/9.3f930309'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/docs.2897e9e6.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/docs.2897e9e6'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/manifest.b7f52b44.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/manifest.b7f52b44'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.2/vendor.ae4be299.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.2/vendor.ae4be299'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/0.8985122d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/0.8985122d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/1.06ee0bed.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/1.06ee0bed'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/10.c7e6c3e5.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/10.c7e6c3e5'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/11.fd21e8e8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/11.fd21e8e8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/12.cb3c1a2d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/12.cb3c1a2d'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/13.1cdad18e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/13.1cdad18e'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/14.fd41ec35.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/14.fd41ec35'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/15.58889e3a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/15.58889e3a'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/16.e2efe67b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/16.e2efe67b'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/17.0d923825.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/17.0d923825'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/18.fa7c7df1.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/18.fa7c7df1'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/19.62eeb5ff.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/19.62eeb5ff'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/2.c10fbd04.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/2.c10fbd04'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/20.861ee4ae.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/20.861ee4ae'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/21.9fa5a6ef.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/21.9fa5a6ef'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/22.5475b341.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/22.5475b341'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/23.56fe1118.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/23.56fe1118'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/24.d3091d84.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/24.d3091d84'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/25.bb881f9f.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/25.bb881f9f'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/26.6c68ad23.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/26.6c68ad23'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/27.dac46d92.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/27.dac46d92'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/28.3b5484f8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/28.3b5484f8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/29.cf5daabc.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/29.cf5daabc'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/3.937606f3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/3.937606f3'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/30.a9cd11af.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/30.a9cd11af'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/31.111340a6.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/31.111340a6'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/4.94654a0e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/4.94654a0e'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/5.f8a38ce8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/5.f8a38ce8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/6.6d779ad8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/6.6d779ad8'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/7.fea19aba.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/7.fea19aba'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/8.4a1e48b3.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/8.4a1e48b3'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/9.3f930309.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/9.3f930309'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/docs.abaf0d65.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/docs.abaf0d65'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/manifest.2b0afab6.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/manifest.2b0afab6'>;
}
declare module 'vue-material/dist/docs/releases/v0.6.3/vendor.ae4be299.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.6.3/vendor.ae4be299'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/avatar.a4498c8a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/avatar.a4498c8a'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/base.695f7a2d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/base.695f7a2d'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/bottom-bar.e6f88ccc.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/bottom-bar.e6f88ccc'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/button-toggle.5458c921.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/button-toggle.5458c921'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/buttons.81edf435.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/buttons.81edf435'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/card.37f54da4.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/card.37f54da4'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/checkbox.7603dc1d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/checkbox.7603dc1d'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/chips.996b2d4b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/chips.996b2d4b'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/dialog.774bdbaf.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/dialog.774bdbaf'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/docs.478f64a5.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/docs.478f64a5'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/file.e75792b4.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/file.e75792b4'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/icon.5330687d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/icon.5330687d'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/image-loader.2b5a107e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/image-loader.2b5a107e'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/ink-ripple.c6c186b1.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/ink-ripple.c6c186b1'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/input.ecca7906.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/input.ecca7906'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/list.21d93484.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/list.21d93484'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/manifest.09510f01.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/manifest.09510f01'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/menu.212fadff.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/menu.212fadff'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/progress.2ff899d0.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/progress.2ff899d0'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/radio.da972ed8.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/radio.da972ed8'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/select.bff7868d.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/select.bff7868d'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/sidenav.5443196c.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/sidenav.5443196c'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/snackbar.00a46162.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/snackbar.00a46162'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/speed-dial.e07af350.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/speed-dial.e07af350'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/spinner.ae9c0ffa.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/spinner.ae9c0ffa'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/subheader.f0a1356a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/subheader.f0a1356a'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/switch.9aa0318e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/switch.9aa0318e'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/table.295127fd.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/table.295127fd'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/tabs.b3bab112.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/tabs.b3bab112'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/themes.cef94272.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/themes.cef94272'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/toolbar.44924cd1.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/toolbar.44924cd1'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/tooltip.1eae832b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/tooltip.1eae832b'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/ui-elements.ac4dc67a.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/ui-elements.ac4dc67a'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/vendor.51aac3ed.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/vendor.51aac3ed'>;
}
declare module 'vue-material/dist/docs/releases/v0.7.0/whiteframe.7fa045b4.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/releases/v0.7.0/whiteframe.7fa045b4'>;
}
declare module 'vue-material/dist/docs/select.a1466fb5.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/select.a1466fb5'>;
}
declare module 'vue-material/dist/docs/sidenav.fba2cd03.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/sidenav.fba2cd03'>;
}
declare module 'vue-material/dist/docs/snackbar.f7ea4b33.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/snackbar.f7ea4b33'>;
}
declare module 'vue-material/dist/docs/speed-dial.dd03eb33.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/speed-dial.dd03eb33'>;
}
declare module 'vue-material/dist/docs/spinner.43051fb4.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/spinner.43051fb4'>;
}
declare module 'vue-material/dist/docs/subheader.5d412f8e.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/subheader.5d412f8e'>;
}
declare module 'vue-material/dist/docs/switch.4548de27.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/switch.4548de27'>;
}
declare module 'vue-material/dist/docs/table.0fb9c164.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/table.0fb9c164'>;
}
declare module 'vue-material/dist/docs/tabs.5e48770b.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/tabs.5e48770b'>;
}
declare module 'vue-material/dist/docs/themes.614919f9.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/themes.614919f9'>;
}
declare module 'vue-material/dist/docs/toolbar.caa5dc64.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/toolbar.caa5dc64'>;
}
declare module 'vue-material/dist/docs/tooltip.0834711f.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/tooltip.0834711f'>;
}
declare module 'vue-material/dist/docs/ui-elements.775ab723.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/ui-elements.775ab723'>;
}
declare module 'vue-material/dist/docs/vendor.a3c44323.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/vendor.a3c44323'>;
}
declare module 'vue-material/dist/docs/whiteframe.65446ff4.js' {
  declare module.exports: $Exports<'vue-material/dist/docs/whiteframe.65446ff4'>;
}
declare module 'vue-material/dist/vue-material.debug.js' {
  declare module.exports: $Exports<'vue-material/dist/vue-material.debug'>;
}
declare module 'vue-material/dist/vue-material.js' {
  declare module.exports: $Exports<'vue-material/dist/vue-material'>;
}
declare module 'vue-material/src/components/mdAvatar/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdAvatar/index'>;
}
declare module 'vue-material/src/components/mdBackdrop/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdBackdrop/index'>;
}
declare module 'vue-material/src/components/mdBottomBar/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdBottomBar/index'>;
}
declare module 'vue-material/src/components/mdButton/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdButton/index'>;
}
declare module 'vue-material/src/components/mdButtonToggle/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdButtonToggle/index'>;
}
declare module 'vue-material/src/components/mdCard/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdCard/index'>;
}
declare module 'vue-material/src/components/mdCheckbox/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdCheckbox/index'>;
}
declare module 'vue-material/src/components/mdChips/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdChips/index'>;
}
declare module 'vue-material/src/components/mdDialog/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdDialog/index'>;
}
declare module 'vue-material/src/components/mdDivider/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdDivider/index'>;
}
declare module 'vue-material/src/components/mdFile/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdFile/index'>;
}
declare module 'vue-material/src/components/mdIcon/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdIcon/index'>;
}
declare module 'vue-material/src/components/mdImage/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdImage/index'>;
}
declare module 'vue-material/src/components/mdInputContainer/common.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdInputContainer/common'>;
}
declare module 'vue-material/src/components/mdInputContainer/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdInputContainer/index'>;
}
declare module 'vue-material/src/components/mdLayout/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdLayout/index'>;
}
declare module 'vue-material/src/components/mdList/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdList/index'>;
}
declare module 'vue-material/src/components/mdList/mdListItem.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdList/mdListItem'>;
}
declare module 'vue-material/src/components/mdMenu/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdMenu/index'>;
}
declare module 'vue-material/src/components/mdProgress/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdProgress/index'>;
}
declare module 'vue-material/src/components/mdRadio/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdRadio/index'>;
}
declare module 'vue-material/src/components/mdSelect/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdSelect/index'>;
}
declare module 'vue-material/src/components/mdSidenav/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdSidenav/index'>;
}
declare module 'vue-material/src/components/mdSnackbar/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdSnackbar/index'>;
}
declare module 'vue-material/src/components/mdSnackbar/manager.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdSnackbar/manager'>;
}
declare module 'vue-material/src/components/mdSpeedDial/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdSpeedDial/index'>;
}
declare module 'vue-material/src/components/mdSpinner/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdSpinner/index'>;
}
declare module 'vue-material/src/components/mdSubheader/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdSubheader/index'>;
}
declare module 'vue-material/src/components/mdSwitch/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdSwitch/index'>;
}
declare module 'vue-material/src/components/mdTable/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdTable/index'>;
}
declare module 'vue-material/src/components/mdTabs/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdTabs/index'>;
}
declare module 'vue-material/src/components/mdToolbar/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdToolbar/index'>;
}
declare module 'vue-material/src/components/mdTooltip/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdTooltip/index'>;
}
declare module 'vue-material/src/components/mdWhiteframe/index.js' {
  declare module.exports: $Exports<'vue-material/src/components/mdWhiteframe/index'>;
}
declare module 'vue-material/src/core/components/mdInkRipple/index.js' {
  declare module.exports: $Exports<'vue-material/src/core/components/mdInkRipple/index'>;
}
declare module 'vue-material/src/core/components/mdTheme/index.js' {
  declare module.exports: $Exports<'vue-material/src/core/components/mdTheme/index'>;
}
declare module 'vue-material/src/core/components/mdTheme/mixin.js' {
  declare module.exports: $Exports<'vue-material/src/core/components/mdTheme/mixin'>;
}
declare module 'vue-material/src/core/components/mdTheme/palette.js' {
  declare module.exports: $Exports<'vue-material/src/core/components/mdTheme/palette'>;
}
declare module 'vue-material/src/core/components/mdTheme/rgba.js' {
  declare module.exports: $Exports<'vue-material/src/core/components/mdTheme/rgba'>;
}
declare module 'vue-material/src/core/index.js' {
  declare module.exports: $Exports<'vue-material/src/core/index'>;
}
declare module 'vue-material/src/core/utils/animationEndEventName.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/animationEndEventName'>;
}
declare module 'vue-material/src/core/utils/debounce.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/debounce'>;
}
declare module 'vue-material/src/core/utils/getClosestVueParent.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/getClosestVueParent'>;
}
declare module 'vue-material/src/core/utils/getImageLightness.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/getImageLightness'>;
}
declare module 'vue-material/src/core/utils/getInViewPosition.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/getInViewPosition'>;
}
declare module 'vue-material/src/core/utils/isArray.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/isArray'>;
}
declare module 'vue-material/src/core/utils/throttle.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/throttle'>;
}
declare module 'vue-material/src/core/utils/transitionEndEventName.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/transitionEndEventName'>;
}
declare module 'vue-material/src/core/utils/uniqueId.js' {
  declare module.exports: $Exports<'vue-material/src/core/utils/uniqueId'>;
}
declare module 'vue-material/src/index.js' {
  declare module.exports: $Exports<'vue-material/src/index'>;
}
