// flow-typed signature: 4ae775c835dd17401cab7e0932e6c66d
// flow-typed version: <<STUB>>/vue-sticky_v^3.1.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-sticky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-sticky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-sticky/dist/vue-sticky' {
  declare module.exports: any;
}

declare module 'vue-sticky/example/index' {
  declare module.exports: any;
}

declare module 'vue-sticky/src/index' {
  declare module.exports: any;
}

declare module 'vue-sticky/webpack.base' {
  declare module.exports: any;
}

declare module 'vue-sticky/webpack.config' {
  declare module.exports: any;
}

declare module 'vue-sticky/webpack.example.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-sticky/dist/vue-sticky.js' {
  declare module.exports: $Exports<'vue-sticky/dist/vue-sticky'>;
}
declare module 'vue-sticky/example/index.js' {
  declare module.exports: $Exports<'vue-sticky/example/index'>;
}
declare module 'vue-sticky/src/index.js' {
  declare module.exports: $Exports<'vue-sticky/src/index'>;
}
declare module 'vue-sticky/webpack.base.js' {
  declare module.exports: $Exports<'vue-sticky/webpack.base'>;
}
declare module 'vue-sticky/webpack.config.js' {
  declare module.exports: $Exports<'vue-sticky/webpack.config'>;
}
declare module 'vue-sticky/webpack.example.config.js' {
  declare module.exports: $Exports<'vue-sticky/webpack.example.config'>;
}
