// flow-typed signature: ca6e342e9faa1bf68391d2a13f650179
// flow-typed version: <<STUB>>/vue2-animate_v^1.0.4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue2-animate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue2-animate' {
  declare module.exports: any;
}
