// flow-typed signature: 643b64ad1d8180a7dc6934d191579064
// flow-typed version: <<STUB>>/vuex_v^2.3.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuex/dist/logger' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.esm' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex' {
  declare module.exports: any;
}

declare module 'vuex/dist/vuex.min' {
  declare module.exports: any;
}

declare module 'vuex/src/helpers' {
  declare module.exports: any;
}

declare module 'vuex/src/index.esm' {
  declare module.exports: any;
}

declare module 'vuex/src/index' {
  declare module.exports: any;
}

declare module 'vuex/src/mixin' {
  declare module.exports: any;
}

declare module 'vuex/src/module/module-collection' {
  declare module.exports: any;
}

declare module 'vuex/src/module/module' {
  declare module.exports: any;
}

declare module 'vuex/src/plugins/devtool' {
  declare module.exports: any;
}

declare module 'vuex/src/plugins/logger' {
  declare module.exports: any;
}

declare module 'vuex/src/store' {
  declare module.exports: any;
}

declare module 'vuex/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuex/dist/logger.js' {
  declare module.exports: $Exports<'vuex/dist/logger'>;
}
declare module 'vuex/dist/vuex.esm.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.esm'>;
}
declare module 'vuex/dist/vuex.js' {
  declare module.exports: $Exports<'vuex/dist/vuex'>;
}
declare module 'vuex/dist/vuex.min.js' {
  declare module.exports: $Exports<'vuex/dist/vuex.min'>;
}
declare module 'vuex/src/helpers.js' {
  declare module.exports: $Exports<'vuex/src/helpers'>;
}
declare module 'vuex/src/index.esm.js' {
  declare module.exports: $Exports<'vuex/src/index.esm'>;
}
declare module 'vuex/src/index.js' {
  declare module.exports: $Exports<'vuex/src/index'>;
}
declare module 'vuex/src/mixin.js' {
  declare module.exports: $Exports<'vuex/src/mixin'>;
}
declare module 'vuex/src/module/module-collection.js' {
  declare module.exports: $Exports<'vuex/src/module/module-collection'>;
}
declare module 'vuex/src/module/module.js' {
  declare module.exports: $Exports<'vuex/src/module/module'>;
}
declare module 'vuex/src/plugins/devtool.js' {
  declare module.exports: $Exports<'vuex/src/plugins/devtool'>;
}
declare module 'vuex/src/plugins/logger.js' {
  declare module.exports: $Exports<'vuex/src/plugins/logger'>;
}
declare module 'vuex/src/store.js' {
  declare module.exports: $Exports<'vuex/src/store'>;
}
declare module 'vuex/src/util.js' {
  declare module.exports: $Exports<'vuex/src/util'>;
}
